import { Roboto } from 'next/font/google'
import Nav from './auth/Nav'
import './globals.css'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`mx-4 bg-gray-200 md:mx-48 xl:mx-96 ${roboto.className}`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
